# WindowsSubStoreæ¨¡æ¿
# https://raw.githubusercontent.com/GitHuber-Aegon/Clash/refs/heads/main/config/WinSubStoreModel.yaml
# å°†ä¸Šé¢åœ°å€æ·»åŠ åˆ°å®¢æˆ·ç«¯SubStoreä½¿ç”¨
# å°†proxy-providersé‡Œé¢url:""ä¸­çš„è®¢é˜…åœ°å€æ›¿æ¢å³å¯

mixed-port: 7890
allow-lan: true
bind-address: '*'
mode: rule
log-level: info
ipv6: true
external-controller: 127.0.0.1:9090

proxy-providers: # è¿œç¨‹ä»£ç†é›†
  provider01: # é›†åˆåç§°
    type: http
    url: "https://api.v1.mk/sub?target=clash&url=è®¢é˜…é“¾æ¥&emoji=true&list=true&udp=true"
    # ä»¥ä¸‹æ–¹æ³•ä»»é€‰å…¶ä¸€âš ï¸æœ‰Clashè®¢é˜…ä¼˜å…ˆä½¿ç”¨æ–¹æ³•äºŒâ—ï¸
    # 1.å¯ä»¥ä½¿ç”¨ä»»æ„ç±»å‹çš„é“¾æ¥ä»…æ›¿æ¢ä¸Šé¢æ–‡å­—ï¼Œå¤šä¸ªé“¾æ¥ä½¿ç”¨è‹±æ–‡ç¬¦å·çš„ç«–æ |éš”å¼€ä¸€èµ·å†™ä¸Šå³å¯
    # 2.Sub-Storeä¸Clashç±»å‹è®¢é˜…é“¾æ¥æ›¿æ¢æ‰æ•´ä¸ªå¼•å·""å†…çš„é“¾æ¥
    path:
    interval: 86400
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204

dns:
  enable: true
  ipv6: true
  listen: 0.0.0.0:53
  default-nameserver:
    - 119.29.29.29
    - 223.5.5.5
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.lan'
    - localhost.ptlogin2.qq.com
    - '+.srv.nintendo.net'
    - '+.stun.playstation.net'
    - '+.msftconnecttest.com'
    - '+.msftncsi.com'
    - '+.xboxlive.com'
    - 'msftconnecttest.com'
    - 'xbox.*.microsoft.com'
    - '*.battlenet.com.cn'
    - '*.battlenet.com'
    - '*.blzstatic.cn'
    - '*.battle.net'
  nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query

proxies: # ä»£ç†èŠ‚ç‚¹
            
proxy-groups: # ç­–ç•¥ç»„
  - name: ğŸ“¶ æµ‹é€Ÿæœ€ä½³
    type: url-test
    proxies:
    url: "http://www.gstatic.com/generate_204"
    interval: 300
    include-all: true
    hidden: true

  - name: â˜‘ï¸ æ‰‹åŠ¨åˆ‡æ¢
    type: select
    proxies:
    include-all: true

  - name: ğŸ—º å¢ƒå¤–æ¼«æ¸¸
    type: select
    proxies:
      - ğŸ“¶ æµ‹é€Ÿæœ€ä½³
      - â˜‘ï¸ æ‰‹åŠ¨åˆ‡æ¢
      - ğŸ‡­ğŸ‡° é¦™æ¸¯
      - ğŸ‡¹ğŸ‡¼ å°æ¹¾
      - ğŸŒ äºšæ´²
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸ
      - ğŸ‡°ğŸ‡· éŸ©å›½
      - ğŸ‡¦ğŸ‡º æ¾³æ´²
      - ğŸŒ ç¾æ´²
      - ğŸ‡ºğŸ‡¸ ç¾å›½
      - ğŸ‡ªğŸ‡º æ¬§æ´²
      - ğŸŒ éæ´²
      - â­• ç›´è¿è¯·æ±‚
      - ğŸš« æ‹’ç»è¯·æ±‚

  - name: ğŸ‡¨ğŸ‡³ ä¸­å›½å¤§é™†
    type: select
    proxies: &D
      - â­• ç›´è¿è¯·æ±‚
      - ğŸš« æ‹’ç»è¯·æ±‚
      - ğŸ—º å¢ƒå¤–æ¼«æ¸¸
      - â˜‘ï¸ æ‰‹åŠ¨åˆ‡æ¢

  - name: ğŸŸ æ¼ç½‘ä¹‹é±¼
    type: select
    proxies:
      *D

  - name: ğŸ„ TMS
    type: select
    proxies: &M
      - ğŸ‡­ğŸ‡° é¦™æ¸¯
      - ğŸ‡¹ğŸ‡¼ å°æ¹¾
      - ğŸ—º å¢ƒå¤–æ¼«æ¸¸
      - â˜‘ï¸ æ‰‹åŠ¨åˆ‡æ¢
      - â­• ç›´è¿è¯·æ±‚
      - ğŸš« æ‹’ç»è¯·æ±‚
    include-all: true
    filter: "ğŸ‡­ğŸ‡°|é¦™æ¸¯|HK|HongKong|ğŸ‡¹ğŸ‡¼|å°æ¹¾|å°ç£|è‡ºç£|TW|TaiWan"

  - name: ğŸŠ Beanfun
    type: select
    proxies:
      *M
    include-all: true
    filter: "ğŸ‡­ğŸ‡°|é¦™æ¸¯|HK|HongKong|ğŸ‡¹ğŸ‡¼|å°æ¹¾|å°ç£|è‡ºç£|TW|TaiWan"

  - name: LeagueClient
    type: select
    proxies: &B
      - ğŸ‡¨ğŸ‡³ ä¸­å›½å¤§é™†
      - ğŸ‡­ğŸ‡° é¦™æ¸¯
      - ğŸ‡¹ğŸ‡¼ å°æ¹¾
      - ğŸŒ äºšæ´²
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸ
      - ğŸ‡°ğŸ‡· éŸ©å›½
      - ğŸ‡¦ğŸ‡º æ¾³æ´²
      - ğŸŒ ç¾æ´²
      - ğŸ‡ºğŸ‡¸ ç¾å›½
      - ğŸ‡ªğŸ‡º æ¬§æ´²
      - ğŸŒ éæ´²
      - ğŸ—º å¢ƒå¤–æ¼«æ¸¸
      - â˜‘ï¸ æ‰‹åŠ¨åˆ‡æ¢
      - â­• ç›´è¿è¯·æ±‚
      - ğŸš« æ‹’ç»è¯·æ±‚
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/LOL.png

  - name: LOL(TM)Client
    type: select
    proxies:
      *B
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/LOL.png

  - name: ğŸ¤– AI
    type: select
    proxies:
      - ğŸŒ ç¾æ´²
      - ğŸ‡ºğŸ‡¸ ç¾å›½
      - ğŸ‡ªğŸ‡º æ¬§æ´²
      - ğŸŒ äºšæ´²
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸ
      - ğŸ‡°ğŸ‡· éŸ©å›½
      - ğŸ‡¦ğŸ‡º æ¾³æ´²
      - ğŸŒ éæ´²
      - ğŸ‡­ğŸ‡° é¦™æ¸¯
      - ğŸ‡¹ğŸ‡¼ å°æ¹¾
      - ğŸ—º å¢ƒå¤–æ¼«æ¸¸
      - â˜‘ï¸ æ‰‹åŠ¨åˆ‡æ¢
      - â­• ç›´è¿è¯·æ±‚
      - ğŸš« æ‹’ç»è¯·æ±‚

  - name: Google
    type: select
    proxies: &G
      - ğŸ—º å¢ƒå¤–æ¼«æ¸¸
      - ğŸ‡­ğŸ‡° é¦™æ¸¯
      - ğŸ‡¹ğŸ‡¼ å°æ¹¾
      - ğŸŒ äºšæ´²
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸ
      - ğŸ‡°ğŸ‡· éŸ©å›½
      - ğŸ‡¦ğŸ‡º æ¾³æ´²
      - ğŸŒ ç¾æ´²
      - ğŸ‡ºğŸ‡¸ ç¾å›½
      - ğŸ‡ªğŸ‡º æ¬§æ´²
      - ğŸŒ éæ´²
      - â˜‘ï¸ æ‰‹åŠ¨åˆ‡æ¢
      - â­• ç›´è¿è¯·æ±‚
      - ğŸš« æ‹’ç»è¯·æ±‚
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Google_Search.png

  - name: YouTube
    type: select
    proxies:
      *G
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/YouTube.png

  - name: Telegram
    type: select
    proxies:
      *G
    icon: https://raw.githubusercontent.com/shindgewongxj/WHATSINStash/main/icon/telegram.png

  - name: ğŸ” åå…«ç¦
    type: select
    proxies:
      *G

  - name: Apple
    type: select
    proxies:
      *B
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Apple_2.png

  - name: Microsoft
    type: select
    proxies:
      *B
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Microsoft.png

  - name: GitHub
    type: select
    proxies:
      *B
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/GitHub.png

  - name: Spotify
    type: select
    proxies:
      *B
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Spotify.png

  - name: Tinder
    type: select
    proxies:
      *B
    icon: https://raw.githubusercontent.com/shindgewongxj/WHATSINStash/main/icon/tinder.png

  - name: ğŸ…¿ï¸ PotPlayer
    type: select
    proxies:
      *B

  - name: âœˆï¸ Airport
    type: select
    proxies:
      *B

  - name: ğŸ“¥ DownloadTools
    type: select
    proxies:
      *B

#  - name: WeChat
#    type: select
#    proxies: &C
#      - ğŸ‡¨ğŸ‡³ ä¸­å›½å¤§é™†
#      - ğŸ‡­ğŸ‡° é¦™æ¸¯
#      - ğŸ‡¹ğŸ‡¼ å°æ¹¾
#      - ğŸ—º å¢ƒå¤–æ¼«æ¸¸
#      - â˜‘ï¸ æ‰‹åŠ¨åˆ‡æ¢
#      - â­• ç›´è¿è¯·æ±‚
#      - ğŸš« æ‹’ç»è¯·æ±‚
#    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/WeChat.png

  - name: çˆ±å¥‡è‰º
    type: select
    proxies: &C
      - ğŸ‡¨ğŸ‡³ ä¸­å›½å¤§é™†
      - ğŸ‡­ğŸ‡° é¦™æ¸¯
      - ğŸ‡¹ğŸ‡¼ å°æ¹¾
      - ğŸ—º å¢ƒå¤–æ¼«æ¸¸
      - â˜‘ï¸ æ‰‹åŠ¨åˆ‡æ¢
      - â­• ç›´è¿è¯·æ±‚
      - ğŸš« æ‹’ç»è¯·æ±‚
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/iQIYI_1.png

  - name: å“”å“©å“”å“©
    type: select
    proxies:
      *C
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/bilibili_3.png

#  - name: ç½‘æ˜“äº‘éŸ³ä¹
#    type: select
#    proxies:
#      *C
#    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Netease_Music.png

  - name: ç™½åå•
    type: select
    proxies:
      *D
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/AdWhite.png

  - name: é»‘åå•
    type: select
    proxies:
      - ğŸš« æ‹’ç»è¯·æ±‚
      - â­• ç›´è¿è¯·æ±‚
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/AdBlack.png

  - name: â­• ç›´è¿è¯·æ±‚
    type: select
    proxies:
      - DIRECT
    hidden: true

  - name: ğŸš« æ‹’ç»è¯·æ±‚
    type: select
    proxies:
      - REJECT-DROP
    hidden: true

  - name: ğŸ‡­ğŸ‡° é¦™æ¸¯
    type: url-test
    url: "http://www.gstatic.com/generate_204"
    interval: 300
    lazy: false
    include-all: true
    filter: "ğŸ‡­ğŸ‡°|é¦™æ¸¯|HK|HongKong"
    hidden: true

  - name: ğŸ‡¹ğŸ‡¼ å°æ¹¾
    type: url-test
    url: "http://www.gstatic.com/generate_204"
    interval: 300
    lazy: false
    include-all: true
    filter: "ğŸ‡¹ğŸ‡¼|å°æ¹¾|å°ç£|è‡ºç£|TW|TaiWan"
    hidden: true

  - name: ğŸŒ äºšæ´²
    type: url-test
    url: "http://www.gstatic.com/generate_204"
    interval: 300
    lazy: true
    include-all: true
    filter: "æ—¥æœ¬|æ–°åŠ å¡|éŸ©|è¶Š|æŸ¬|é©¬æ¥è¥¿äºš|æ³°|å°åº¦|è²|å°å°¼|äºšç¾å°¼äºš|æ ¼é²å‰äºš|åœŸè€³å…¶|æ²™ç‰¹|ä¼Šæ‹‰å…‹|ä»¥è‰²åˆ—|é˜¿æ›¼|é˜¿æ‹‰ä¼¯è”åˆ|å¡å¡”å°”|æ–¯å¦|æœæ‹œ|è¿ªæ‹œ"
    hidden: true

  - name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬
    type: url-test
    url: "http://www.gstatic.com/generate_204"
    interval: 300
    lazy: true
    include-all: true
    filter: "ğŸ‡¯ğŸ‡µ|æ—¥æœ¬|JP|Japan"
    hidden: true

  - name: ğŸ‡¸ğŸ‡¬ ç‹®åŸ
    type: url-test
    url: "http://www.gstatic.com/generate_204"
    interval: 300
    lazy: true
    include-all: true
    filter: "ğŸ‡¯ğŸ‡µ|æ–°åŠ å¡|ç‹®åŸ|ç…åŸ|SG|Singapore"
    hidden: true

  - name: ğŸ‡°ğŸ‡· éŸ©å›½
    type: url-test
    url: "http://www.gstatic.com/generate_204"
    interval: 300
    lazy: true
    include-all: true
    filter: "ğŸ‡°ğŸ‡·|éŸ©|éŸ“|KR|Korea"
    hidden: true

  - name: ğŸ‡¦ğŸ‡º æ¾³æ´²
    type: url-test
    url: "http://www.gstatic.com/generate_204"
    interval: 300
    lazy: true
    include-all: true
    filter: "ğŸ‡¦ğŸ‡º|æ¾³å¤§åˆ©äºš|æ¾³å¤§åˆ©äº|æ–°è¥¿å…°|æ–°è¥¿è˜­|çº½è¥¿å…°|ç´è¥¿è˜­|AU|AUS|Australia"
    hidden: true

  - name: ğŸŒ ç¾æ´²
    type: url-test
    url: "http://www.gstatic.com/generate_204"
    interval: 300
    lazy: true
    include-all: true
    filter: "ç¾å›½|åŠ æ‹¿å¤§|é˜¿æ ¹å»·|ç§˜é²|å“¥ä¼¦æ¯”äºš|å±åœ°é©¬æ‹‰|å„ç“œå¤šå°”|å“¥æ–¯è¾¾é»åŠ |å¢¨è¥¿å“¥|æ™ºåˆ©|ç»åˆ©ç»´äºš|ä¹Œæ‹‰åœ­|å·´è¥¿"
    hidden: true

  - name: ğŸ‡ºğŸ‡¸ ç¾å›½
    type: url-test
    url: "http://www.gstatic.com/generate_204"
    interval: 300
    lazy: true
    include-all: true
    filter: "ç¾å›½|ç¾åˆ©åš|US|USA"
    hidden: true

  - name: ğŸ‡ªğŸ‡º æ¬§æ´²
    type: url-test
    url: "http://www.gstatic.com/generate_204"
    interval: 300
    lazy: true
    include-all: true
    filter: "å¾·å›½|æ³•å›½|ç‘å£«|è‹±å›½|çˆ±å°”å…°|å†°å²›|æ³¢å…°|æ„å¤§åˆ©|è¥¿ç­ç‰™|è·å…°|èŠ¬å…°|å¥¥åœ°åˆ©|ç«‹é™¶å®›|ç‘å…¸|å¸Œè…Š|æ‹‰è„±ç»´äºš|æŒªå¨|ä¸¹éº¦|æ¯”åˆ©æ—¶|å¢æ£®å ¡|é©¬å…¶é¡¿|é˜¿å°”å·´å°¼äºš|è‘¡è„ç‰™|ä¹Œå…‹å…°|æ‘©å°”å¤šç“¦|çˆ±æ²™å°¼äºš|å…‹ç½—åœ°äºš|æ–¯æ´›æ–‡å°¼äºš|ä¿„ç½—æ–¯|ä¿åŠ åˆ©äºš|å¡å°”ç»´äºš|å¡æµ¦è·¯æ–¯"
    hidden: true

  - name: ğŸŒ éæ´²
    type: url-test
    url: "http://www.gstatic.com/generate_204"
    interval: 300
    lazy: true
    include-all: true
    filter: "åŸƒåŠ|å°¼æ—¥åˆ©äºš|æ‘©æ´›å“¥|å—é"
    hidden: true

rule-providers: # è¿œç¨‹è§„åˆ™é›†

  WhiteList:
    type: http
    behavior: classical
    format: text
    url: https://raw.githubusercontent.com/GitHuber-Aegon/Clash/main/ruleslist/White.list
    interval: 86400

  TMS:
    type: http
    behavior: classical
    format: text
    url: https://raw.githubusercontent.com/GitHuber-Aegon/Clash/main/ruleslist/TMS.list
    interval: 86400

  BeanfunHK:
    type: http
    behavior: classical
    format: text
    url: https://raw.githubusercontent.com/GitHuber-Aegon/Clash/main/ruleslist/BeanfunHK.list
    interval: 86400

  BeanfunTW:
    type: http
    behavior: classical
    format: text
    url: https://raw.githubusercontent.com/GitHuber-Aegon/Clash/main/ruleslist/BeanfunTW.list
    interval: 86400

  LeagueClient:
    type: http
    behavior: classical
    format: text
    url: https://raw.githubusercontent.com/GitHuber-Aegon/Clash/main/ruleslist/LeagueClient.list
    interval: 86400

  LOL(TM)Client:
    type: http
    behavior: classical
    format: text
    url: https://raw.githubusercontent.com/GitHuber-Aegon/Clash/main/ruleslist/LeagurofLegends(TM)Client.list
    interval: 86400

  AI:
    type: http
    behavior: classical
    format: text
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/AI.list
    interval: 86400

  Google:
    type: http
    behavior: classical
    format: text
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Google/Google.list
    interval: 86400

  YouTube:
    type: http
    behavior: classical
    format: text
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/YouTube/YouTube.list
    interval: 86400

  Telegram:
    type: http
    behavior: classical
    format: text
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Telegram/Telegram.list
    interval: 86400

  18:
    type: http
    behavior: classical
    format: text
    url: https://raw.githubusercontent.com/GitHuber-Aegon/Clash/refs/heads/main/ruleslist/18.list
    interval: 86400

  Apple:
    type: http
    behavior: classical
    format: text
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Apple/Apple.list
    interval: 86400

  OneDrive:
    type: http
    behavior: classical
    format: text
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/OneDrive/OneDrive.list
    interval: 86400

  Microsoft:
    type: http
    behavior: classical
    format: text
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Microsoft/Microsoft.list
    interval: 86400

  GitHub:
    type: http
    behavior: classical
    format: text
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/GitHub/GitHub.list
    interval: 86400

  Spotify:
    type: http
    behavior: classical
    format: text
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Spotify/Spotify.list
    interval: 86400

  Tinder:
    type: http
    behavior: classical
    format: text
    url: https://raw.githubusercontent.com/GitHuber-Aegon/Clash/main/ruleslist/Tinder.list
    interval: 86400

  PotPlayer:
    type: http
    behavior: classical
    format: text
    url: https://raw.githubusercontent.com/GitHuber-Aegon/Clash/main/ruleslist/PotPlayer.list
    interval: 86400

  Airport:
    type: http
    behavior: classical
    format: text
    url: https://raw.githubusercontent.com/GitHuber-Aegon/Clash/refs/heads/main/ruleslist/Airport.list
    interval: 86400

  DownloadTools:
    type: http
    behavior: classical
    format: text
    url: https://raw.githubusercontent.com/GitHuber-Aegon/Clash/main/ruleslist/DownloadTools.list
    interval: 86400

#  WeChat:
#    type: http
#    behavior: classical
#    format: text
#    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/WeChat/WeChat.list
#    interval: 86400

  iQIYI:
    type: http
    behavior: classical
    format: text
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/iQIYI/iQIYI.list
    interval: 86400

  BiliBili:
    type: http
    behavior: classical
    format: text
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/BiliBili/BiliBili.list
    interval: 86400

#  NetEaseMusic:
#    type: http
#    behavior: classical
#    format: text
#    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/NetEaseMusic/NetEaseMusic.list
#    interval: 86400

  WallOutside:
    type: http
    behavior: classical
    format: text
    url: https://raw.githubusercontent.com/GitHuber-Aegon/Clash/main/ruleslist/WallOutside.list
    interval: 86400

  Global:
    type: http
    behavior: classical
    format: text
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Global/Global.list
    interval: 86400

  Lan: # å±€åŸŸç½‘
    type: http
    behavior: classical
    format: text
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Lan/Lan.list
    interval: 86400

  China:
    type: http
    behavior: classical
    format: text
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/China/China.list
    interval: 86400

#  IOS_Update: # IOSæ›´æ–°
#    type: http
#    behavior: classical
#    format: text
#    url: https://raw.githubusercontent.com/GitHuber-Aegon/Clash/main/ruleslist/IOS_Update.list
#    interval: 86400

#  BanProgramAD: # å±è”½APPå¼€å±å¹¿å‘Š
#    type: http
#    behavior: classical
#    format: text
#    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list
#    interval: 86400

  BanAD: # å±è”½å¹¿å‘Š
    type: http
    behavior: classical
    format: text
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
    interval: 86400

rules: # è§„åˆ™åŒ¹é…
  - RULE-SET,WhiteList,ç™½åå•
  - RULE-SET,TMS,ğŸ„ TMS
  - RULE-SET,BeanfunHK,ğŸŠ Beanfun
  - RULE-SET,BeanfunTW,ğŸŠ Beanfun
  - RULE-SET,LeagueClient,LeagueClient
  - RULE-SET,LOL(TM)Client,LOL(TM)Client
  - RULE-SET,Apple,Apple
  - RULE-SET,OneDrive,Microsoft
  - RULE-SET,Microsoft,Microsoft
  - RULE-SET,GitHub,GitHub
  - RULE-SET,Spotify,Spotify
  - RULE-SET,Tinder,Tinder
  - RULE-SET,PotPlayer,ğŸ…¿ï¸ PotPlayer
  - RULE-SET,Airport,âœˆï¸ Airport
  - RULE-SET,DownloadTools,ğŸ“¥ DownloadTools
  - RULE-SET,AI,ğŸ¤– AI
#  - RULE-SET,X,X
  - RULE-SET,YouTube,YouTube
  - RULE-SET,Google,Google
  - RULE-SET,Telegram,Telegram
  - RULE-SET,18,ğŸ” åå…«ç¦
#  - RULE-SET,WeChat,WeChat
  - RULE-SET,iQIYI,çˆ±å¥‡è‰º
  - RULE-SET,BiliBili,å“”å“©å“”å“©
#  - RULE-SET,NetEaseMusic,ç½‘æ˜“äº‘éŸ³ä¹
  - RULE-SET,WallOutside,ğŸ—º å¢ƒå¤–æ¼«æ¸¸
  - RULE-SET,Global,ğŸ—º å¢ƒå¤–æ¼«æ¸¸
#  - RULE-SET,IOS_Update,é»‘åå•
#  - RULE-SET,BanProgramAD,é»‘åå•
  - RULE-SET,BanAD,é»‘åå•
  - GEOIP,Lan,DIRECT,no-resolve
  - GEOIP,CN,DIRECT,no-resolve
  - MATCH,ğŸŸ æ¼ç½‘ä¹‹é±¼